-- IDs use standard SQL identity (works on H2 and Postgres)
CREATE TABLE countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iso2 VARCHAR(2) NOT NULL UNIQUE,
  name TEXT NOT NULL
);

-- Core catalog keyed by HS code + light product typing for UX/analytics
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hs_code VARCHAR(10) NOT NULL,              -- Prefer 6–10 digit HS/HTS
  name TEXT NOT NULL,                        -- e.g., "Smartphone", "Laptop"
  product_type VARCHAR(16) NOT NULL,         -- PHONE | LAPTOP | TABLET | TV | MONITOR
  brand VARCHAR(100),                        -- Optional metadata
  model VARCHAR(100)
);

-- Duty rules (mostly ad valorem for electronics).
-- Keep generic rule fields so your existing service code stays similar.
CREATE TABLE tariff_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin_iso2 VARCHAR(2) NOT NULL,
  dest_iso2   VARCHAR(2) NOT NULL,
  hs_code     VARCHAR(10) NOT NULL,
  rule_type   VARCHAR(20) NOT NULL,          -- 'ad_valorem' | 'specific' | 'compound'
  rate_value  NUMERIC(12,6) NOT NULL,        -- percent or amount depending on unit
  rate_unit   TEXT NOT NULL,                 -- 'PERCENT' | 'USD_PER_UNIT' | 'SGD_PER_UNIT' | 'PERCENT+USD_PER_UNIT'
  valid_from  DATE NOT NULL,
  valid_to    DATE,
  CONSTRAINT ck_rule_type CHECK (rule_type IN ('ad_valorem','specific','compound')),
  CONSTRAINT ck_rate_unit_by_type CHECK (
    (rule_type = 'ad_valorem' AND rate_unit = 'PERCENT')
    OR (rule_type = 'specific' AND rate_unit IN ('USD_PER_UNIT','SGD_PER_UNIT'))
    OR (rule_type = 'compound' AND rate_unit IN ('PERCENT+USD_PER_UNIT','PERCENT+SGD_PER_UNIT'))
  )
);

-- Replace alcohol excise with a generic indirect tax (e.g., SG GST).
-- If you only want customs duty, you can omit this table.
CREATE TABLE indirect_tax_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_iso2 VARCHAR(2) NOT NULL,
  tax_type     VARCHAR(20) NOT NULL,         -- 'GST' | 'VAT'
  rate_value   NUMERIC(12,6) NOT NULL,       -- 0.090000 = 9%
  rate_unit    TEXT NOT NULL,                -- always 'PERCENT' for GST/VAT
  valid_from   DATE NOT NULL,
  valid_to     DATE,
  CONSTRAINT ck_tax_type CHECK (tax_type IN ('GST','VAT')),
  CONSTRAINT ck_tax_unit CHECK (rate_unit = 'PERCENT')
);

-- (Optional but handy) Capture calculation inputs for auditability
CREATE TABLE calculations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hs_code VARCHAR(10) NOT NULL,
  origin_iso2 VARCHAR(2) NOT NULL,
  dest_iso2   VARCHAR(2) NOT NULL,
  quantity INT NOT NULL,
  declared_value_per_unit_usd NUMERIC(14,4) NOT NULL,  -- CIF per unit
  calc_date DATE NOT NULL DEFAULT CURRENT_DATE
);

-- (Optional) Store results you return to clients for traceability
CREATE TABLE calculation_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calculation_id BIGINT NOT NULL,
  base_duty NUMERIC(14,4) NOT NULL,
  indirect_tax NUMERIC(14,4) NOT NULL,       -- e.g., GST amount (0 if N/A)
  total NUMERIC(14,4) NOT NULL,
  rule_applied TEXT NOT NULL,                 -- e.g., "0% ad valorem (HTS 8517.12)"
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seeds
INSERT INTO countries (iso2, name) VALUES ('SG','Singapore');
INSERT INTO countries (iso2, name) VALUES ('US','United States');

-- Minimal HS seeds for electronics (use your precise codes as you refine)
INSERT INTO products (hs_code, name, product_type, brand, model) VALUES
('8517.12', 'Smartphones', 'PHONE', NULL, NULL),
('8471.30', 'Laptops/Portable computers', 'LAPTOP', NULL, NULL),
('8471.41', 'Tablets/Other ADP machines', 'TABLET', NULL, NULL),
('8528.72', 'Television receivers', 'TV', NULL, NULL),
('8528.52', 'Monitors (excl. TV)', 'MONITOR', NULL, NULL);

-- Example tariff rules (placeholders; set real rates in your data load step)
-- SG -> US (HTSUS), US -> SG (HS SG). Electronics are often 0% ad valorem, but keep the shape flexible.
-- INSERT INTO tariff_rules (...) VALUES (...);

-- Example indirect tax: GST for Singapore (adjust rate/date as needed)
-- If you don't want to compute GST, skip this seed.
-- INSERT INTO indirect_tax_rules (country_iso2, tax_type, rate_value, rate_unit, valid_from)
-- VALUES ('SG', 'GST', 0.090000, 'PERCENT', DATE '2025-01-01');
