-- V2__add_products_and_tariffs.sql
-- Migration for countries, products, tariff rules, indirect taxes, and calculations

-- =====================
-- Countries
-- =====================
CREATE TABLE IF NOT EXISTS countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iso2 VARCHAR(2) NOT NULL UNIQUE,
  name TEXT NOT NULL
);

-- =====================
-- Products
-- =====================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hs_code VARCHAR(10) NOT NULL,
  name TEXT NOT NULL,
  product_type VARCHAR(16) NOT NULL,
  brand VARCHAR(100),
  model VARCHAR(100)
);

-- =====================
-- Tariff Rules
-- =====================
CREATE TABLE IF NOT EXISTS tariff_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin_iso2 VARCHAR(2) NOT NULL,
  dest_iso2   VARCHAR(2) NOT NULL,
  hs_code     VARCHAR(10) NOT NULL,
  rule_type   VARCHAR(20) NOT NULL,          -- 'ad_valorem' | 'specific' | 'compound'
  rate_value  NUMERIC(12,6) NOT NULL,        -- percent or amount depending on unit
  rate_unit   TEXT NOT NULL,                 -- 'PERCENT' | 'USD_PER_UNIT' | etc.
  valid_from  DATE NOT NULL,
  valid_to    DATE,
  CONSTRAINT ck_rule_type CHECK (rule_type IN ('ad_valorem','specific','compound'))
);

-- =====================
-- Indirect Tax Rules (optional: GST/VAT)
-- =====================
CREATE TABLE IF NOT EXISTS indirect_tax_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_iso2 VARCHAR(2) NOT NULL,
  tax_type     VARCHAR(20) NOT NULL,         -- 'GST' | 'VAT'
  rate_value   NUMERIC(12,6) NOT NULL,       -- e.g., 0.090000 = 9%
  rate_unit    TEXT NOT NULL DEFAULT 'PERCENT',
  valid_from   DATE NOT NULL,
  valid_to     DATE,
  CONSTRAINT ck_tax_type CHECK (tax_type IN ('GST','VAT'))
);

-- =====================
-- Calculations (user inputs)
-- =====================
CREATE TABLE IF NOT EXISTS calculations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hs_code VARCHAR(10) NOT NULL,
  origin_iso2 VARCHAR(2) NOT NULL,
  dest_iso2   VARCHAR(2) NOT NULL,
  quantity INT NOT NULL,
  declared_value_per_unit_usd NUMERIC(14,4) NOT NULL,
  calc_date DATE NOT NULL DEFAULT CURRENT_DATE
);

-- =====================
-- Calculation Audits (results)
-- =====================
CREATE TABLE IF NOT EXISTS calculation_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calculation_id BIGINT NOT NULL,
  base_duty NUMERIC(14,4) NOT NULL,
  indirect_tax NUMERIC(14,4) NOT NULL,
  total NUMERIC(14,4) NOT NULL,
  rule_applied TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================
-- Seeds
-- =====================
INSERT INTO countries (iso2, name) VALUES ('SG','Singapore')
    ON CONFLICT (iso2) DO NOTHING;
INSERT INTO countries (iso2, name) VALUES ('US','United States')
    ON CONFLICT (iso2) DO NOTHING;

INSERT INTO products (hs_code, name, product_type) VALUES
('8517.12', 'Smartphones', 'PHONE'),
('8471.30', 'Laptops/Portable computers', 'LAPTOP'),
('8473.30', 'CPU', 'COMPONENT'),
('8473.40', 'GPU', 'COMPONENT'),
('8473.50', 'RAM', 'COMPONENT')
ON CONFLICT DO NOTHING;

-- Example tariff: Singapore → US laptops 0% duty
INSERT INTO tariff_rules (origin_iso2, dest_iso2, hs_code, rule_type, rate_value, rate_unit, valid_from)
VALUES ('SG','US','8471.30','ad_valorem',0.00,'PERCENT','2025-01-01');
