spring:
  application:
    name: tariff-server
  datasource:
    url: jdbc:postgresql://db.xizwjutjdldhrthleubs.supabase.co:5432/postgres
    username: postgres
    password: jY8MbHb4bg_hij!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080

# Development profile configuration
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tariffdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update