spring.application.name=tariff-server

# --- Database Connection ---
spring.datasource.url=jdbc:postgresql://db.xizwjutjdldhrthleubs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=jY8MbHb4bg_hij!
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=update   # for dev: auto create/update tables
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=none 
#-- two lines of code above just for testing for now

