-- IDs use standard SQL identity (works on H2 and Postgres)
CREATE TABLE countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iso2 VARCHAR(2) NOT NULL UNIQUE,
  name TEXT NOT NULL
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hs_code VARCHAR(10) NOT NULL,
  name TEXT NOT NULL
);

-- Use VARCHAR + CHECK instead of Postgres ENUM (works on both)
CREATE TABLE tariff_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin_iso2 VARCHAR(2) NOT NULL,
  dest_iso2   VARCHAR(2) NOT NULL,
  hs_code     VARCHAR(10) NOT NULL,
  rule_type   VARCHAR(20) NOT NULL,
  rate_value  NUMERIC(12,6) NOT NULL,
  rate_unit   TEXT NOT NULL,           -- e.g., PERCENT, USD_PER_LITER, SGD_PER_LAA
  valid_from  DATE NOT NULL,
  valid_to    DATE,
  CONSTRAINT ck_rule_type CHECK (rule_type IN ('ad_valorem','specific','compound'))
);

CREATE TABLE excise_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_iso2 VARCHAR(2) NOT NULL,
  hs_code      VARCHAR(10) NOT NULL,
  rate_value   NUMERIC(12,6) NOT NULL,
  rate_unit    TEXT NOT NULL,          -- e.g., SGD_PER_LAA, USD_PER_WINE_GAL
  valid_from   DATE NOT NULL,
  valid_to     DATE
);

-- Seed WITHOUT "ON CONFLICT" (Flyway runs once, so duplicates won't reinsert)
INSERT INTO countries (iso2, name) VALUES ('SG','Singapore');
INSERT INTO countries (iso2, name) VALUES ('US','United States');

INSERT INTO products (hs_code, name) VALUES ('2203','Beer made from malt');
INSERT INTO products (hs_code, name) VALUES ('2204','Wine of fresh grapes');
INSERT INTO products (hs_code, name) VALUES ('2208','Spirits, liqueurs');
